export { default as Dashboard } from "./Dashboard";
export { default as StatsCards } from "./StatsCards";
export { default as AttendanceOverview } from "./AttendanceOverview";
export { default as ResultsOverview } from "./ResultsOverview";
export { default as AssignmentsOverview } from "./AssignmentsOverview";
export { default as FeesOverview } from "./FeesOverview";
export { default as UpcomingClasses } from "./UpcomingClasses";
export { default as UpcomingEvents } from "./UpcomingEvents";
export { default as RecentNotices } from "./RecentNotices";